process_polaris_file('../Topics/1_plus_polaris.csv', '../Outputs/1_plus_polaris.csv', 2.6)
process_polaris_file('../Topics/1_minus_polaris.csv', '../Outputs/1_minus_polaris.csv', 4.3)
process_polaris_file('../Topics/2_plus_polaris.csv', '../Outputs/2_plus_polaris.csv', 3)
process_polaris_file('../Topics/2_minus_polaris.csv', '../Outputs/2_minus_polaris.csv', 2.6)
process_polaris_file('../Topics/3_plus_polaris.csv', '../Outputs/3_plus_polaris.csv', 2.2)
process_polaris_file('../Topics/3_minus_polaris.csv', '../Outputs/3_minus_polaris.csv', 3.0)