function process_polaris_file(fname, ofname, offset)
	M_input = csvread(fname);
	
	seq = M_input(:, 1);
	seq = ((seq - seq(1)) / 1000000000) - offset;
	pos_x = M_input(:, 11);
	pos_y = M_input(:, 12);
	pos_z = M_input(:, 13);
	
	%x_max = max(pos_x);
	%y_max = max(pos_y);
	%z_max = max(pos_z);
	
	%x_min = min(pos_x);
	%y_min = min(pos_y);
	%z_min = min(pos_z);
	
	%min_norm = min(min(x_min, y_min), z_min);
	%max_norm = max(max(x_max, y_max), z_max) - min_norm;
	
	%pos_x = (pos_x - min_norm) / max_norm;
	%pos_y = (pos_y - min_norm) / max_norm;
	%pos_z = (pos_z - min_norm) / max_norm;
	%set(gca, 'YLim', [0, 0.05]);
	
	mask_1 = (seq >= 15 & seq <= 20);
	mask_2 = (seq >= 35 & seq <= 40);
	mask_3 = (seq >= 55 & seq <= 60);
	mask_4 = (seq >= 75 & seq <= 80);
	mask_5 = (seq >= 95 & seq <= 100);
	mask_6 = (seq >= 115 & seq <= 120);
	mask_7 = (seq >= 135 & seq <= 140);
	mask_8 = (seq >= 155 & seq <= 160);
	mask_9 = (seq >= 175 & seq <= 180);
	mask_10 = (seq >= 195 & seq <= 200);
	
	t_1 = seq(mask_1);
	x_1 = pos_x(mask_1);
	y_1 = pos_y(mask_1);
	z_1 = pos_z(mask_1);
	t_2 = seq(mask_2);
	x_2 = pos_x(mask_2);
	y_2 = pos_y(mask_2);
	z_2 = pos_z(mask_2);
	t_3 = seq(mask_3);
	x_3 = pos_x(mask_3);
	y_3 = pos_y(mask_3);
	z_3 = pos_z(mask_3);
	t_4 = seq(mask_4);
	x_4 = pos_x(mask_4);
	y_4 = pos_y(mask_4);
	z_4 = pos_z(mask_4);
	t_5 = seq(mask_5);
	x_5 = pos_x(mask_5);
	y_5 = pos_y(mask_5);
	z_5 = pos_z(mask_5);
	t_6 = seq(mask_6);
	x_6 = pos_x(mask_6);
	y_6 = pos_y(mask_6);
	z_6 = pos_z(mask_6);
	t_7 = seq(mask_7);
	x_7 = pos_x(mask_7);
	y_7 = pos_y(mask_7);
	z_7 = pos_z(mask_7);
	t_8 = seq(mask_8);
	x_8 = pos_x(mask_8);
	y_8 = pos_y(mask_8);
	z_8 = pos_z(mask_8);
	t_9 = seq(mask_9);
	x_9 = pos_x(mask_9);
	y_9 = pos_y(mask_9);
	z_9 = pos_z(mask_9);
	t_10 = seq(mask_10);
	x_10 = pos_x(mask_10);
	y_10 = pos_y(mask_10);
	z_10 = pos_z(mask_10);
	
	all_t = [t_1; t_2; t_3; t_4; t_5; t_6; t_7; t_8; t_9; t_10];
	all_x = [x_1; x_2; x_3; x_4; x_5; x_6; x_7; x_8; x_9; x_10];
	all_y = [y_1; y_2; y_3; y_4; y_5; y_6; y_7; y_8; y_9; y_10];
	all_z = [z_1; z_2; z_3; z_4; z_5; z_6; z_7; z_8; z_9; z_10];
	
	figure('Name', 'X');
	plot(seq, pos_x);
	hold on;
	plot(all_t, all_x, '.');
	xlabel('Time (sec)');
	ylabel('X-Displacement (m)');
	hold off;
	
	figure('Name', 'Y');
	plot(seq, pos_y);
	hold on;
	plot(all_t, all_y, '.');
	xlabel('Time (sec)');
	ylabel('Y-Displacement (m)');
	hold off;
	
	figure('Name', 'Z');
	plot(seq, pos_z);
	hold on;
	plot(all_t, all_z, '.');
	xlabel('Time (sec)');
	ylabel('Z-Displacement (m)');
	hold off;
	
	std_x_1 = std(x_1);
	avg_x_1 = mean(x_1);
	std_y_1 = std(y_1);
	avg_y_1 = mean(y_1);
	std_z_1 = std(z_1);
	avg_z_1 = mean(z_1);
	std_x_2 = std(x_2);
	avg_x_2 = mean(x_2);
	std_y_2 = std(y_2);
	avg_y_2 = mean(y_2);
	std_z_2 = std(z_2);
	avg_z_2 = mean(z_2);
	std_x_3 = std(x_3);
	avg_x_3 = mean(x_3);
	std_y_3 = std(y_3);
	avg_y_3 = mean(y_3);
	std_z_3 = std(z_3);
	avg_z_3 = mean(z_3);
	std_x_4 = std(x_4);
	avg_x_4 = mean(x_4);
	std_y_4 = std(y_4);
	avg_y_4 = mean(y_4);
	std_z_4 = std(z_4);
	avg_z_4 = mean(z_4);
	std_x_5 = std(x_5);
	avg_x_5 = mean(x_5);
	std_y_5 = std(y_5);
	avg_y_5 = mean(y_5);
	std_z_5 = std(z_5);
	avg_z_5 = mean(z_5);
	std_x_6 = std(x_6);
	avg_x_6 = mean(x_6);
	std_y_6 = std(y_6);
	avg_y_6 = mean(y_6);
	std_z_6 = std(z_6);
	avg_z_6 = mean(z_6);
	std_x_7 = std(x_7);
	avg_x_7 = mean(x_7);
	std_y_7 = std(y_7);
	avg_y_7 = mean(y_7);
	std_z_7 = std(z_7);
	avg_z_7 = mean(z_7);
	std_x_8 = std(x_8);
	avg_x_8 = mean(x_8);
	std_y_8 = std(y_8);
	avg_y_8 = mean(y_8);
	std_z_8 = std(z_8);
	avg_z_8 = mean(z_8);
	std_x_9 = std(x_9);
	avg_x_9 = mean(x_9);
	std_y_9 = std(y_9);
	avg_y_9 = mean(y_9);
	std_z_9 = std(z_9);
	avg_z_9 = mean(z_9);
	std_x_10 = std(x_10);
	avg_x_10 = mean(x_10);
	std_y_10 = std(y_10);
	avg_y_10 = mean(y_10);
	std_z_10 = std(z_10);
	avg_z_10 = mean(z_10);
	
	big_matrix = [avg_x_1, std_x_1, avg_y_1, std_y_1, avg_z_1, std_z_1;
		avg_x_2, std_x_2, avg_y_2, std_y_2, avg_z_2, std_z_2;
		avg_x_3, std_x_3, avg_y_3, std_y_3, avg_z_3, std_z_3;
		avg_x_4, std_x_4, avg_y_4, std_y_4, avg_z_4, std_z_4;
		avg_x_5, std_x_5, avg_y_5, std_y_5, avg_z_5, std_z_5;
		avg_x_6, std_x_6, avg_y_6, std_y_6, avg_z_6, std_z_6;
		avg_x_7, std_x_7, avg_y_7, std_y_7, avg_z_7, std_z_7;
		avg_x_8, std_x_8, avg_y_8, std_y_8, avg_z_8, std_z_8;
		avg_x_9, std_x_9, avg_y_9, std_y_9, avg_z_9, std_z_9;
		avg_x_10, std_x_10, avg_y_10, std_y_10, avg_z_10, std_z_10];
	
	csvwrite(ofname, big_matrix);
end